### ISSUE TITLE
The  compiled-time source generator failed while generate Folders 

### ISSUE THREAD

**Issue by MoMakkawi** [dotnet/roslyn-sdk#1070] opened 2023-03-12 09:32 UTC
### Is there an efficient way to make the [Source Generators](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) **generate folders at compile time, not just files?**

Note: I know that I can use System.IO, but I do not think that this is the best solution, and I prefer to write as follows:

`context.AddSource(" folder/ file.g.cs", "source");`

**Comment by sharwell** [comment] 2023-03-13 16:17
Duplicate of https://github.com/dotnet/roslyn/issues/66122

**Closed by sharwell** 2023-03-13 16:17 UTC
