### ISSUE TITLE
Analyzer template has a failing unit test

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn-sdk#617] opened 2020-09-03 15:53 UTC
When creating a "Analyzer with Code Fix" project, two unit tests are created, but only one passes.

        [TestMethod]
        public async Task TestMethod2()
        {
            var test = @"
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Diagnostics;

    namespace ConsoleApplication1
    {
        class {|#0:TypeName|}
        {   
        }
    }";

            var fixtest = @"
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using System.Diagnostics;

    namespace ConsoleApplication1
    {
        class TYPENAME
        {   
        }
    }";

            var expected = VerifyCS.Diagnostic("Analyzer1").WithLocation(0).WithArguments("TypeName");
            await VerifyCS.VerifyCodeFixAsync(test, expected, fixtest);
        }
    }

Error message:

> Assert.AreEqual failed. Expected:<0>. Actual:<1>. Context: Diagnostics of test state
>     Context: Verifying exclusions in <auto-generated> code
>     Mismatch between number of diagnostics returned, expected "0" actual "1"

Using VS 16.8.0 Preview 2.1

**Comment by sharwell** [comment] 2020-09-03 16:04
Duplicate of #603

**Closed by sharwell** 2020-09-03 16:04 UTC
