### ISSUE TITLE
Source Generators sample doesn't run generator with "dotnet build"

### ISSUE THREAD

**Issue by dagood** [dotnet/roslyn-sdk#524] opened 2020-05-03 23:29 UTC
I'm able to get Source Generators to work in VS preview (per [the blog post](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/)), however it doesn't work with `dotnet run` unless I've already used VS to build it.

I put together a pasteable repro in Docker with the samples checked into this repo, to make sure the issues I'm hitting happen even with a completely fresh repro:

```
docker run -it --rm mcr.microsoft.com/dotnet/core/sdk:5.0 bash -c '
  set -ex
  apt update
  apt install -y wget unzip

  commit=11a4dc4e7b5ac2e1d3cce7cf5533cb51b295df64
  wget https://github.com/dotnet/roslyn-sdk/archive/$commit.zip
  mkdir -p $HOME/roslyn-sdk
  unzip -q $commit.zip -d $HOME/roslyn-sdk
  # Move the sample out of the repo.
  mkdir -p $HOME/sample
  cp -r $HOME/roslyn-sdk/roslyn-sdk-$commit/samples/CSharp/SourceGenerators $HOME/sample

  dotnet --info

  cd $HOME/sample/SourceGenerators
  dotnet build'
```

Relevant-looking snippets:

```
+ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.3.20216.6
```

```
+ dotnet build
Microsoft (R) Build Engine version 16.6.0-preview-20181-02+9f3e4e725 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj (in 1.54 sec).
  Restored /root/sample/SourceGenerators/SourceGeneratorSamples/SourceGeneratorSamples.csproj (in 5.06 sec).
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  SourceGeneratorSamples -> /root/sample/SourceGenerators/SourceGeneratorSamples/bin/Debug/netstandard2.0/SourceGeneratorSamples.dll
UseAutoNotifyGenerator.cs(2,7): error CS0246: The type or namespace name 'AutoNotify' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]
UseXmlSettingsGenerator.cs(2,7): error CS0246: The type or namespace name 'AutoSettings' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]
UseAutoNotifyGenerator.cs(9,10): error CS0246: The type or namespace name 'AutoNotifyAttribute' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]
UseAutoNotifyGenerator.cs(9,10): error CS0246: The type or namespace name 'AutoNotify' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]
UseAutoNotifyGenerator.cs(12,10): error CS0246: The type or namespace name 'AutoNotifyAttribute' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]
UseAutoNotifyGenerator.cs(12,10): error CS0246: The type or namespace name 'AutoNotify' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]
UseAutoNotifyGenerator.cs(12,21): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?) [/root/sample/SourceGenerators/GeneratedDemo/GeneratedDemo.csproj]

Build FAILED.
```

Seems related to the issue being discussed in https://github.com/dotnet/roslyn-sdk/issues/520, but I think that was on an earlier commit of the samples.

@cartermp, you mentioned this worked for you at https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/#comment-5627, any idea what's going wrong for me?

**Comment by tpetrina** [comment] 2020-05-04 11:55
Following instructions on macOS using `dotnet` CLI doesn't work. The code in the `samples` works when compiled with the CLI _inside_ the repo, but when moved out (just c/p sample dir) it stops working. Something to do with Arcade MSBuild probably running analyzers and which is missing in the default MSBuild tasks/targets.

**Comment by cartermp** [comment] 2020-05-04 17:55
Yeah I think this is inherent to the repo being arcade-enabled. @sharwell @jmarolf y'all have any feels about this?

**Comment by dagood** [comment] 2020-05-04 18:01
> Yeah I think this is inherent to the repo being arcade-enabled.

Maybe I'm nitpicking language here, but that doesn't sound quite right... sure, the repo being arcade-enabled might make it more difficult to author a sample that works inside this repo, but the Source Generators feature as a whole doesn't work at all for me outside VS preview, and that's what I'm looking for.

(I was only using the sample from this repo because it was called out specifically as working--I get the same behavior from the sample in the blog post.)

**Comment by cartermp** [comment] 2020-05-04 18:06
@dagood I confirmed that I can build the sample within this repo on a mac, no VS required. So I don't think there's anything specific to VS involved here aside from getting IntelliSense to work. So you're unable to build anything unless it is only within this repo and within VS?

**Comment by dagood** [comment] 2020-05-04 18:13
My experience:

|   | In this repo | Outside this repo (same behavior with blog post sample)
| --- | --- | ---
| VS preview | ❔ (did not attempt) | ✔️ 
| `dotnet build` | ✔️ | ❌ compile errors imply generator did not run

The repro command I posted is for the failing cell.

**Comment by dagood** [comment] 2020-05-04 18:17
The kind thing I think will resolve this is figuring out what it is that Arcade's doing that makes this work, and putting it in this sample and in the blog post sample. (If it's incompatible with Arcade, only the blob post sample if no compatible way to do it can be found.)

**Comment by dagood** [comment] 2020-05-04 18:27
> the Source Generators feature as a whole doesn't work at all for me outside VS preview

I see I made things unclear with this, sorry--"for me" means not using Arcade, since it is not intended for general use.

**Comment by centreboard** [comment] 2020-05-04 18:57
It looks to me like Arcade is adding a Package reference to [Microsoft.Net.Compilers.Toolset 3.7.0-1.20220.1](https://github.com/dotnet/arcade/blob/17288f02e0801a6bd8aad8ead173f20ca40acdb7/src/Microsoft.DotNet.Arcade.Sdk/tools/Compiler.props#L5)
So it then builds using the compiler from that nuget package?
Changing this line to `false` causes the build (with the .Net 5 preview) to fail in the cloned rolsyn-sdk repository
https://github.com/dotnet/roslyn-sdk/blob/11a4dc4e7b5ac2e1d3cce7cf5533cb51b295df64/eng/Versions.props#L11

**Comment by dagood** [comment] 2020-05-04 19:11
Nice! That works for me with my repro command (https://github.com/dotnet/roslyn-sdk/commit/5cb9f5cd2881a1ae8dfbcea0990ef7341af45033) `GeneratedSample.csproj`:

```diff
 <Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
     <OutputType>Exe</OutputType>
     <TargetFramework>netcoreapp3.1</TargetFramework>
     <LangVersion>preview</LangVersion>
   </PropertyGroup>
 
+  <PropertyGroup>
+    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json ;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
+  </PropertyGroup>
 
   <ItemGroup>
     <AdditionalFiles Include="MainSettings.xmlsettings" />
     <None Include="MainSettings.xmlsettings">
       <CopyToOutputDirectory>Always</CopyToOutputDirectory>
     </None>
   </ItemGroup>
 
+  <ItemGroup>
+    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.7.0-1.20220.1" PrivateAssets="all" />
+  </ItemGroup>
 
   <ItemGroup>
     <ProjectReference Include="..\SourceGeneratorSamples\SourceGeneratorSamples.csproj" 
                       OutputItemType="Analyzer"
                       ReferenceOutputAssembly="false" />
   </ItemGroup>
 
 </Project>
```

**Comment by centreboard** [comment] 2020-05-04 19:15
Testing locally I think that [3.6.0-3.final](https://www.nuget.org/packages/Microsoft.Net.Compilers.Toolset/3.6.0-3.final) from nuget is sufficient

**Comment by cartermp** [comment] 2020-05-04 20:29
Heya, just tried this out. Going to hunt it down, but it might have been some error in shipping .NET 5 preview 3, since VS uses the correct compiler. In the meantime the package is a workaround for non-VS scenarios.

**Comment by dominikjeske** [comment] 2020-11-20 20:00
I'm having same issue on 3.8 and MsBuild 16.8 but workaround is not working for me. Cloned repo is working but when moved to other location it is failing. I tried to add this to demo project but it is not working for me.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Net.Compilers.Toolset" Version="3.8.0" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json ;$(RestoreAdditionalProjectSources)</RestoreAdditionalProjectSources>
  </PropertyGroup>
```

I have same problems with my sample project https://github.com/dominikjeske/Samples/tree/main/SourceGenerators. It is weird for me that other solutions like this https://github.com/mostmand/Cloneable are working both in VS and MsBuild and I don't see any spetial configuration (there is RestoreAdditionalProjectSources in this project but it is working even after commenting this line). Any ideas how to make it work from CLI?

**Comment by sharwell** [comment] 2020-12-23 15:29
This appears to be resolved by updating to the non-preview builds supporting source generators.

**Closed** 2020-12-23 15:29 UTC
Labels: Area-Source Generators

**Comment by DanielUhlik** [comment] 2021-04-06 11:28
Any updates? I have same problem with `Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET`
