### ISSUE TITLE
Roslyn SDK templates use TFM with out-of-support runtime

### ISSUE THREAD

**Issue by timheuer** [dotnet/roslyn-sdk#1135] opened 2023-12-05 16:13 UTC
The current analyzer SDK templates are using TFMs that are out of support.  What this results in is in using the latest VS and adding the component (.NET Compiler SDK) and creating a new analyzer, Visual Studio immediately gives you a warning that you may not have the runtime installed...and offers an in-product acquisition experience, which guides you to install something that is out-of-support.

Recommendation:
Audit the templates for 17.9 and update to supported TFMs minimum being net6.0 target IMO.

**Comment by mavasani** [comment] 2023-12-05 16:31
@sharwell

**Comment by sharwell** [comment] 2023-12-06 18:28
Duplicate of #1131

**Closed by sharwell** 2023-12-06 18:28 UTC
