### ISSUE TITLE
C# code generator doesn't work with WPF projects.

### ISSUE THREAD

**Issue by sameerdband** [dotnet/roslyn-sdk#647] opened 2020-10-27 15:14 UTC
Create a new project for source code generation.
Create a new WPF project and add the source code generation project as analyzer.
Build the project.
Build fails stating it couldn't find class/assembly.
Same thing works if we use a Console application instead of WPF application.

**Comment by sharwell** [comment] 2020-12-23 04:47
Duplicate of dotnet/wpf#3404

**Closed by sharwell** 2020-12-23 04:47 UTC
