### ISSUE TITLE
Missing method in standard Analyzer + Code Fix template Test project

### ISSUE THREAD

**Issue by Joe4evr** [dotnet/roslyn-sdk#529] opened 2020-05-12 22:02 UTC
**Version Used**: 
Microsoft Visual Studio Community 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22

**Steps to Reproduce**:

1. Create a new project using the Analyzer + Code Fix template
2. Build it

**Expected Behavior**:
Project builds successfully.

**Actual Behavior**:
The build fails because the method `CreateReferenceFromFile` used in `DiagnosticVerifier.Helper.cs` does not exist.
![](https://files.gitter.im/dotnet/roslyn/uJCf/image.png)

**Comment by sharwell** [comment] 2020-05-13 06:55
Duplicate of #493

**Comment by sharwell** [comment] 2020-05-13 06:56
The templates were already updated for the 16.6 release :+1: 

We're still investigating some remaining issues and trying to find a way to add tests for this feature.

**Closed by sharwell** 2020-05-13 06:55 UTC
