### ISSUE TITLE
Build failures when source generator references local .NET Standard 2.0 projects

### ISSUE THREAD

**Issue by scharnyw** [dotnet/roslyn-sdk#869] opened 2021-06-21 03:28 UTC
I'm seeking a clearer answer to [this discussion](https://github.com/dotnet/roslyn/discussions/47517) on the Roslyn repo. Specifically, if it's possible to add local `ProjectReference` dependencies to a source generator.

I have a solution with 2 projects: a console application and a source generator. The console app depends on the source generator to generate code (i.e. as an analyzer). Now I would like to add some dependencies to the source generator itself. [This answer](https://github.com/dotnet/roslyn/discussions/47517#discussioncomment-64145) explains how to add `PackageReference` from NuGet, but it does not explain how to add `ProjectReference` to a local project. I tried doing it the naive way like this in my source generator .csproj:

    <ItemGroup>
      <ProjectReference Include="..\SharedDependency\SharedDependency.csproj" />
    </ItemGroup>

where "SharedDependency" is a normal .NET Standard 2.0 class library project.

But I get the following when trying to build with both dotnet CLI and msbuild:

> CSC : warning CS8785: Generator 'TestGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception
was of type 'FileNotFoundException' with message 'Could not load file or assembly 'SharedDependency, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of it
s dependencies. The system cannot find the file specified.'

Is there any way to make this work? A clearer answer or links to documentation would be greatly appreciated.

**Comment by sharwell** [comment] 2021-06-23 17:08
Duplicate of https://github.com/dotnet/roslyn/discussions/47517

**Comment by sharwell** [comment] 2021-06-23 17:09
I don't currently have an answer for the above, but when we finally figure it out it will be posted on the linked discussion. 👍

**Closed by sharwell** 2021-06-23 17:08 UTC
