### ISSUE TITLE
No new package on NuGet.org

### ISSUE THREAD

**Issue by agocke** [dotnet/roslyn-sdk#1083] opened 2023-04-02 19:12 UTC
It's been over a year since this package had updates on NuGet.org, but the source generator APIs have undergone significant revisions, notably the introduction of incremental generators.

This package should have an update published ASAP.

**Comment by Youssef1313** [comment] 2023-04-04 18:05
Duplicate of https://github.com/dotnet/roslyn-sdk/issues/1047

@agocke The way to go for now is to use `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json` and get latest prerelease.

In case you don't like to add the extra source for the whole codebase in NuGet.config, you could add `		<RestoreAdditionalProjectSources>https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json</RestoreAdditionalProjectSources>` to the test project.

**Comment by agocke** [comment] 2023-04-04 18:12
Even with that change, there is still missing support, like the lack of an API for incremental generators.

**Comment by sharwell** [comment] 2023-04-05 16:17
@agocke Incremental generators are supported by defining the verifier class in your test project. It's a pretty small change from testing a previous `ISourceGenerator`:
https://github.com/dotnet/roslyn-analyzers/commit/8a090706

**Comment by agocke** [comment] 2023-04-05 18:34
Where are the docs on this?

**Comment by sharwell** [comment] 2023-04-05 19:19
I removed the `ISourceGenerator` type constraint in #1084, so this is now a duplicate.

**Comment by sharwell** [comment] 2023-04-05 19:19
Duplicate of #1047

**Closed by sharwell** 2023-04-05 19:19 UTC
