### ISSUE TITLE
CodeStyle tests fail on Mono

### ISSUE THREAD

**Issue by tmat** [dotnet/roslyn-sdk#237] opened 2018-11-28 02:37 UTC
```
System.TypeInitializationException : The type initializer for 'Microsoft.CodeAnalysis.Testing.MetadataReferences' threw an exception.\n---- System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
Stack trace
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1[TVerifier].CreateSolution (Microsoft.CodeAnalysis.ProjectId projectId, System.String language) [0x0008a] in <dd18822397554aca8b5e68ec5a8f6fe9>:0 
  at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1[TVerifier].CreateProjectImpl (System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] sources, System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] additionalFiles, Microsoft.CodeAnalysis.MetadataReference[] additionalMetadataReferences, System.String language) [0x0001b] in <dd18822397554aca8b5e68ec5a8f6fe9>:0 
  at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1[TVerifier].CreateProject (System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] sources, System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] additionalFiles, Microsoft.CodeAnalysis.MetadataReference[] additionalMetadataReferences, System.String language) [0x0000b] in <dd18822397554aca8b5e68ec5a8f6fe9>:0 
  at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1[TVerifier].GetSolution (System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] sources, System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] additionalFiles, Microsoft.CodeAnalysis.MetadataReference[] additionalMetadataReferences) [0x00025] in <dd18822397554aca8b5e68ec5a8f6fe9>:0 
  at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1[TVerifier].GetSortedDiagnosticsAsync (System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] sources, System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] additionalFiles, Microsoft.CodeAnalysis.MetadataReference[] additionalMetadataReferences, System.Collections.Immutable.ImmutableArray`1[T] analyzers, System.Threading.CancellationToken cancellationToken) [0x00001] in <dd18822397554aca8b5e68ec5a8f6fe9>:0 
  at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1[TVerifier].VerifyDiagnosticsAsync (System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] sources, System.ValueTuple`2[System.String,Microsoft.CodeAnalysis.Text.SourceText][] additionalFiles, Microsoft.CodeAnalysis.MetadataReference[] additionalMetadataReferences, Microsoft.CodeAnalysis.Testing.DiagnosticResult[] expected, System.Threading.CancellationToken cancellationToken) [0x0004f] in <dd18822397554aca8b5e68ec5a8f6fe9>:0 
  at Microsoft.CodeAnalysis.Testing.CodeFixTest`1[TVerifier].RunAsync (System.Threading.CancellationToken cancellationToken) [0x002ca] in <bea6109ce718443bafa8672a3f0e818d>:0 
  at Microsoft.CodeAnalysis.CodeStyle.FormattingAnalyzerTests.TestCaseCorrection () [0x0007c] in <99a0aee16a8940b390b7bf4f0389ae59>:0 
```

**Comment by sharwell** [comment] 2019-09-16 19:30
@tmat The failure to load Microsoft.VisualBasic stems from failing to copy the Microsoft.VisualBasic.dll implementation from the NuGet package to the build output directory. The copy does not occur because of this message in the build:

> Encountered conflict between 'Platform:Microsoft.VisualBasic.dll' and 'CopyLocal:C:\\Users\\sam\\.nuget\\packages\\microsoft.visualbasic\\10.0.1\\lib\\netstandard1.3\\Microsoft.VisualBasic.dll'. Choosing 'Platform:Microsoft.VisualBasic.dll' because AssemblyVersion '10.0.4.0' is greater than '10.0.1.0'.

It appears that the builds for net472 and netcoreapp2.2 both include a reference assembly for Microsoft.VisualBasic, suggesting that the runtime will provide the implementation for it. However, Mono does not provide this implementation, leading to a runtime failure. I'm not sure what the expected resolution here is since the runtime fails to implement the specification we're compiling against.

**Comment by tmat** [comment] 2019-09-16 19:38
Package Microsoft.VisualBasic 10.0.1 does not have netstandard2.0 target. Version 10.3.0 does. I wonder if this would be fixed by referencing the newer one.

**Comment by sharwell** [comment] 2019-10-10 18:37
This issue can only be resolved by Mono shipping a copy of Microsoft.VisualBasic. I submitted #388 so the impact of the Mono bug is limited to VB testing. Closing the remaining item as external.

**Comment by sharwell** [comment] 2019-10-10 18:37
Duplicate of mono/mono#10679

**Closed by sharwell** 2019-10-10 18:37 UTC
Labels: Area-MS.CA.Testing
