### ISSUE TITLE
Syntax Visualizer in VS 2019 does not display any symbol information

### ISSUE THREAD

**Issue by SENya1990** [dotnet/roslyn-sdk#546] opened 2020-06-07 13:10 UTC
Hi. I have a problem with Syntax Visualizr in Visual Studio 2019 (latest update 16.6.1).
I try to look for semantic information for simple class declaration in a simple console application(.Net Framework 4.7.2) :
```csharp
public class SomeClass
{
}
```
But I just get an empty useless window like this:
![изображение](https://user-images.githubusercontent.com/7687400/83969450-cb928180-a8d8-11ea-93a3-2918f7e4806d.png)

I also have VS 2017 (update 15.9.21) installed on the same machine and when I do this in VS 2017 everything works fine:
![изображение](https://user-images.githubusercontent.com/7687400/83969504-1ad8b200-a8d9-11ea-9818-5ba337b4fd3b.png)

Could you please make Syntax Visualizer in VS 2019 work like in VS 2017

**Comment by jmarolf** [comment] 2020-06-08 02:25
duplicate of #504

**Closed by jmarolf** 2020-06-08 02:25 UTC
