### ISSUE TITLE
`dotnet build` fails for analyzers

### ISSUE THREAD

**Issue by MisinformedDNA** [dotnet/roslyn-sdk#622] opened 2020-09-08 18:08 UTC
The analyzer template (in VS 16.8.0 Preview 2.1) builds in VS, but fails with an error at the command line.

> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(80,5): error MSB4062: The "CompareCommonBuildTaskVersion" task could not be loaded from the assembly C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.dll. Could not load file or assembly 'System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Vsix\Analyzer1.Vsix.csproj]

Here is the build output with no changes to the code/project:

> ~\Source\Repos\Analyzer1> dotnet build
> Microsoft (R) Build Engine version 16.8.0-preview-20414-02+a55ce4fbb for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   All projects are up-to-date for restore.
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(80,5): error MSB4062: The "CompareCommonBuildTaskVersion" task could not be loaded from the assembly C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.dll. Could not load file or assembly 'System.IO.Packaging, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Vsix\Analyzer1.Vsix.csproj]
>   You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
>   Analyzer1 -> C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1\bin\Debug\netstandard2.0\Analyzer1.dll
>   Analyzer1.CodeFixes -> C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.CodeFixes\bin\Debug\netstandard2.0\Analyzer1.CodeFixes.dll
>   Analyzer1.Test -> C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Test\bin\Debug\netcoreapp2.0\Analyzer1.Test.dll
>   Analyzer1.Package -> C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Package\bin\Debug\netstandard2.0\Analyzer1.Package.dll
> 
> Build FAILED.
> 
> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(80,5): error MSB4062: The "CompareCommonBuildTaskVersion" task could not be loaded from the assembly C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.dll. Could not load file or assembly 'System.IO.Packaging, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Vsix\Analyzer1.Vsix.csproj]
>     0 Warning(s)
>     1 Error(s)
> 

I don't think I need .NET 5, so I created a global.json with

```json
{
    "sdk": {
      "version": "3.1.200",
      "rollForward": "latestFeature",
      "allowPrerelease": false
    }
  }
```

Building seems to get farther, but still results in an error:

> C:\repos\PulumiAnalyzers [master ≡ +1 ~0 -0 !]> dotnet build
> Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Determining projects to restore...
>   Restored C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.Vsix\MisinformedDNA.PulumiAnalyzers.Vsix.csproj (in 738 ms).
>   Restored C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.Test\MisinformedDNA.PulumiAnalyzers.Test.csproj (in 11.7 sec).
>   3 of 5 projects are up-to-date for restore.
> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(80,5): error MSB4062: The "CompareCommonBuildTaskVersion" task could not be loaded from the assembly C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.dll. Could not load file or assembly 'System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.Vsix\MisinformedDNA.PulumiAnalyzers.Vsix.csproj]
>   MisinformedDNA.PulumiAnalyzers -> C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\bin\Debug\netstandard2.0\MisinformedDNA.PulumiAnalyzers.dll
>   MisinformedDNA.PulumiAnalyzers.CodeFixes -> C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.CodeFixes\bin\Debug\netstandard2.0\MisinformedDNA.PulumiAnalyzers.CodeFixes.dll
>   MisinformedDNA.PulumiAnalyzers.Package -> C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.Package\bin\Debug\netstandard2.0\MisinformedDNA.PulumiAnalyzers.Package.dll
>   MisinformedDNA.PulumiAnalyzers.Test -> C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.Test\bin\Debug\netcoreapp3.1\MisinformedDNA.PulumiAnalyzers.Test.dll
> 
> Build FAILED.
> 
> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(80,5): error MSB4062: The "CompareCommonBuildTaskVersion" task could not be loaded from the assembly C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.dll. Could not load file or assembly 'System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\repos\PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers\MisinformedDNA.PulumiAnalyzers.Vsix\MisinformedDNA.PulumiAnalyzers.Vsix.csproj]
>     0 Warning(s)
>     1 Error(s)

Is this expected?

Workaround: Specify the package for build. (i.e. `dotnet build .\Analyzer1\Analyzer1.Package\`)

**Comment by sharwell** [comment] 2020-09-08 18:12
Does `dotnet msbuild` work?

**Comment by MisinformedDNA** [comment] 2020-09-08 18:21
Same error message.

**Comment by sharwell** [comment] 2020-09-08 18:35
The VSIX project has the following:

```
<PackageReference Include="Microsoft.VSSDK.BuildTools" Version="15.1.192" PrivateAssets="all" />
```

If you update this reference to version 16.7.3069, does it work?

**Comment by MisinformedDNA** [comment] 2020-09-08 18:48
Nope, but I get a different error:

> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\build\Microsoft.VSSDK.BuildTools.targets(15,5): error MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild. [C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Vsix\Analyzer1.Vsix.csproj]
> C:\Users\50587\.nuget\packages\microsoft.vssdk.buildtools\16.7.3069\build\Microsoft.VSSDK.BuildTools.targets(15,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files\dotnet\sdk\3.1.401\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property. [C:\Users\50587\Source\Repos\Analyzer1\Analyzer1\Analyzer1.Vsix\Analyzer1.Vsix.csproj]

I get the same error with `dotnet build` and `dotnet msbuild`.

**Comment by sharwell** [comment] 2020-12-23 05:03
It looks like `dotnet build` doesn't like the VSIX project. My recommendation is creating a solution filter (*.slnf) containing all the projects from the main solution exception for the VSIX project, and then use that project when building with the `dotnet` tool.

**Comment by sharwell** [comment] 2020-12-23 15:24
Duplicate of dotnet/sdk#12421

**Closed by sharwell** 2020-12-23 15:24 UTC

**Comment by dsplaisted** [comment] 2021-01-18 22:42
As I just [commented](https://github.com/dotnet/sdk/issues/12421#issuecomment-762500359) on the other issue, the problem is that the Microsoft.VSSDK.BuildTools NuGet package doesn't support the `dotnet` version of MSBuild (which runs on .NET 5 / .NET Core instead of .NET Framework).

**Comment by jwooley** [comment] 2021-11-14 03:05
It appears the default templates for the Roslyn SDK (Code Fix for example) that ship with VS 2022 still target the older buildtools version and show this error. Consider updating the default templates with the newer reference.
