### ISSUE TITLE
Building a newly created Roslyn Analyzer project fails with An attempt was made to load a program with an incorrect format

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/roslyn-sdk#956] opened 2022-01-27 18:13 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Building-a-newly-created-Roslyn-Analyzer/1626031)._

---
[severity:I'm unable to use this version]
I created a new Analyzer Project and tried to build it. That failed with

```
Build started...
1>------ Build started: Project: eufdsAnalyzer.Vsix, Configuration: Debug Any CPU ------
2>------ Build started: Project: eufdsAnalyzer.Package, Configuration: Debug Any CPU ------
1>C:\Users\Lukas\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VsSDK.targets(84,5): error MSB4062: The "CompareBuildTaskVersion" task could not be loaded from the assembly C:\Users\Lukas\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll. Could not load file or assembly 'file:///C:\Users\Lukas\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
1>Done building project "eufdsAnalyzer.Vsix.csproj" -- FAILED.
2>eufdsAnalyzer.Package -> C:\Projekte\TestApps\eufdsAnalyzer\eufdsAnalyzer.Package\bin\Debug\netstandard2.0\eufdsAnalyzer.Package.dll
========== Build: 1 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========

```

When opening the mentioned DLL I can see that it is a 32-bit DLL:

! [image.png] (https://aka.ms/dc/image?name=B518d631f95ab4a178bbebdae3eefa62c637764676202646457_20211230-142700-image.png&tid=518d631f95ab4a178bbebdae3eefa62c637764676202646457)

That's my guess for why it fails

---
#### Feedback Bot on 12/31/2021, 00:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/3/2022, 10:54 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/4/2022, 11:13 AM: 

<p>A fix for this issue has been internally implemented and is being prepared for release. We’ll update you once it becomes available for download.</p>

---
### Original Solutions
(no solutions)

**Comment by sharwell** [comment] 2022-01-31 17:47
Duplicate of #934

**Closed by sharwell** 2022-01-31 17:47 UTC
Labels: duplicate
