### ISSUE TITLE
New Analyzer and CodeFix solution fails build

### ISSUE THREAD

**Issue by vritant24** [dotnet/roslyn-sdk#523] opened 2020-05-03 05:32 UTC
**Version Used**: 
Version 16.6.0 Preview 5.0
**Steps to Reproduce**:

1. create new Analyzer and Codefix project
2. Build solution

**Expected Behavior**:
solution builds

**Actual Behavior**:
The following packages couldn't be found in the local feed in the Analyzer.Test project
```
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Analyzer.Testing.MSTest" Version="1.0.1-beta1.*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest" Version="1.0.1-beta1.*" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeRefactoring.Testing.MSTest" Version="1.0.1-beta1.*" />
```
I added the the myget feed for roslyn: https://dotnet.myget.org/F/roslyn-analyzers/api/v3/index.json
which successfully restored the packages, but the test project doesn't build due to there being an error in the following using in the generated AnalyzerUnitTests.cs file.
```
using Verify = Microsoft.CodeAnalysis.CSharp.CodeFix.Testing.MSTest.CodeFixVerifier<
    NamespaceFolderSyncAnalyzer.NamespaceSyncAnalyzerAnalyzer,
    NamespaceFolderSyncAnalyzer.NamespaceSyncAnalyzerCodeFixProvider>;
```
The error is: 
```
CS0234	The type or namespace name 'CodeFix' does not exist in the namespace 'Microsoft.CodeAnalysis.CSharp' (are you missing an assembly reference?)	NamespaceSyncAnalyzer.Test	C:\Users\Administrator\source\repos\NamespaceSyncAnalyzer\NamespaceSyncAnalyzer\NamespaceSyncAnalyzer.Test\NamespaceSyncAnalyzerUnitTests.cs	3	Active
```

**Comment by sharwell** [comment] 2020-05-03 20:28
@madsk do you know how we can add tests for validity of project and item templates? I'm having trouble even with manual testing.

**Comment by vritant24** [comment] 2020-05-04 17:26
Looks like there are problems in building on the latest enterprise version 16.5.4 too.

**Comment by sharwell** [comment] 2020-05-11 16:45
@madskristensen we're seeing more reports of issues related to these templates. It would be a huge help if you could assist in establishing a reliable test process for them.

**Comment by sharwell** [comment] 2020-05-11 16:45
🔗 Also have a report of a refactoring project failing: https://developercommunity.visualstudio.com/content/problem/970816/cant-build-refactoring-project.html

**Comment by madskristensen** [comment] 2020-05-11 16:56
@tinaschrepfer any ideas?

**Comment by sharwell** [comment] 2020-05-23 00:09
Duplicate of #514

**Closed by sharwell** 2020-05-23 00:09 UTC
Labels: Area-Templates
