### ISSUE TITLE
Analyzer With CodeFix Template does not build

### ISSUE THREAD

**Issue by 333fred** [dotnet/roslyn-sdk#935] opened 2021-12-13 04:53 UTC
Repro Steps:

1. Open VS 2022.
2. Create a new Analyzer + CodeFix (.NET Standard) C# project.
3. Hit Build.

## Expected

Projects to build.

## Actual

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4062	The "CompareBuildTaskVersion" task could not be loaded from the assembly %HOME%\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll. Could not load file or assembly 'file:///%HOME%\.nuget\packages\microsoft.vssdk.buildtools\15.1.192\tools\VSSDK\Microsoft.VisualStudio.Sdk.BuildTasks.15.0.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
```

**Comment by sharwell** [comment] 2022-01-21 23:39
Duplicate of #934

**Closed by sharwell** 2022-01-21 23:39 UTC
Labels: duplicate
